######################################
#     House Points Configuration     #
#        by Kimberly Boynton         #
######################################

# This section is configuration to setup houses.  They can be any name you would like,
# but whatever you name them must also appear on the sign for points.

# If you name them something too long to fit on a minecraft sign, then you will not be
# able to make a points sign.

# The points portion of this updates on load and unload.

# The block can be set to anything in the Material enum of spigot:
# https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Material.html

# ChatColor is the color that the house will appear when in chat.  Pick this from ChatColor enum.

# Short cut is a short cut you can use when doing the /house command to replace the
# house so you don't have to type it out.
#
# custom-item is the ability to use custom models with an armor stand. Since there are two ways of doing this,
# I have set it up so you can do it both ways.
#
# The first way uses Optifine where it renames a block and places it as a helmet
# For this, {rank} needs to be located where you will rename it and the rank will be:
# 1 = 1st place, 2 = 2nd etc...
#
# The second way uses the Custom Model Data on Item Meta and sets the id.
# For the Custom Item Meta you will set the original ID for 1st place, and you need
# at least 3 more slots (All IDs must be 7 digits long)
# ie: 1000001 = 1st gryffindor, 1000001 = 2nd gryffindor, 1000003 = 3rd gryffindor, 1000004 = 4th gryffindor,
#     1000005 = 1st ravenclaw, 1000006 = 2nd ravenclaw ... etc
# You only need to put the 1st place number, the rest will be done for you, this is the id that you put into the
# resource pack json for the specific block type.
# https://www.planetminecraft.com/forums/communities/texturing/new-1-14-custom-item-models-tuto-578834/
Houses:
  Gryffindor:
    points: 0
    material: RED_WOOL
    chatColor: DARK_RED
    shortcut: g
    custom-item:
      rename: gryffindor-{rank}
      id: 1000001
  Ravenclaw:
    points: 0
    material: BLUE_WOOL
    chatColor: DARK_BLUE
    shortcut: r
    custom-item:
      rename: ravenclaw-{rank}
      id: 1000005
  Hufflepuff:
    points: 0
    material: YELLOW_WOOL
    chatColor: GOLD
    shortcut: h
    custom-item:
      rename: hufflepuff-{rank}
      id: 1000009
  Slytherin:
    points: 0
    material: GREEN_WOOL
    chatColor: DARK_GREEN
    shortcut: s
    custom-item:
      rename: slytherin-{rank}
      id: 1000013

custom-item:
  material: STONE
  no-points: 1000000
  rename: no-points
  x: .5
  y: 0
  z: .5

# This list can be as long as you like, add this in the instance that another
# language community would like to change the word for adding or subtracting points.
# WARNING: MUST BE IN LOWER CASE
positive:
- add
- plus
- "+"
- give
negative:
- take
- remove
- subtract
- "-"

# This section is a representation of all the strings used in the plugin, and will allow users to alter as they see fit,
# messages, it will also allow them to hook in with the message ids to a custom language. The messageids are the path
# except for messages. as it would be in a bukkit config.
messages:
  # Give/Take sections of messages have the ability to add variables, and you can rearrange them at will.
  # Variables will only be filled in when present. Otherwise they will fill with an empty string.
  # Here are the variables you can use in the string.
  # {player} = player who receives points
  # {points} = points given/taken
  # {reason} = reason
  # {house}= house
  # {hc}= house color
  # {giver}= person who altered the points
  # Also supports minecraft colors with & as the color variable.
  give:
    houseOnly: "&e{giver}&r has rewarded {hc}{house}&r with &e{points}&r!"
    playerNoReason: "&e{giver}&r has rewarded &e{player}&r {hc}{house}&r with &e{points}&r!"
    playerWithReason: "&e{giver}&r has rewarded &e{player}&r {hc}{house}&r with &e{points}&r for {reason}!"
    reasonOnly: "&e{giver}&r has rewarded {hc}{house}&r with &e{points}&r for {reason}!"
  take:
    houseOnly: "&e{giver}&r has taken &e{points}&r from {hc}{house}&r!"
    playerNoReason: "&e{giver}&r has taken &e{points}&r from &e{player}&r in {hc}{house}&r!"
    playerWithReason: "&e{giver}&r has taken &e{points}&r from &e{player}&r in {hc}{house}&r for {reason}!"
    reasonOnly: "&e{giver}&r has taken &e{points}&r from {hc}{house}&r for {reason}!"
  permission:
    no_permission_command: "&cYou do not have permission to perform this command!"
    no_permission_action: "&cYou do not have permission to do that!"
  command:
    syntax: "&7Correct House Points Syntax is /points [+/-] [house] [points] (player) (reason)"
    not_house: "&cThat doesn't appear to be a house nor a shortcut for a house!"
    event_cancelled: "&cYour event got cancelled by another plugin!"
  listener:
    wallsign: "&cOnly wall signs are supported."

# Block or Item_rename or Item_NBT. Block uses minecraft blocks to choose, and Item will place an item on an itemstand.
pointType: Block
# If points will be represented above the signs or not.
# Turn this to false if you just want signs.
pointRepresentation: true

# If this is false, 0 points will not be represented as no blocks / ahve a 0 representation for items.
# True to have 0 points have its own indicator.
noPointsRepresentation: true

# If a call below requires async, you can turn this on to make the points command run in async.
async: false

consoleSender: The Gods Above
MessageColor: light purple
StandingsTitle: "   [Current House Standings]"
UseTitle: true
Title:
  title: [House Points]
  color: dark purple

Locations:
