name: HousePoints
version: 1.2.0
author: iarepandemonium
description: A plugin for house points.
main: com.knockturnmc.TheHousePoints.HousePoints
commands:
  points:
    description: add/remove points