name: HousePoints
version: 5.0.0
author: iarepandemonium
description: A plugin for house points.
softdepend:
  - Multiverse-Core
main: net.pandette.housepoints.PointsPlugin
api-version: 1.20
load: POSTWORLD
commands:
  points:
    description: add/remove points