name: HousePoints
version: 3.0.5
author: iarepandemonium
description: A plugin for house points.
main: net.pandette.housepoints.PointsPlugin
api-version: 1.13
commands:
  points:
    description: add/remove points